### ISSUE TITLE
TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on linux

### ISSUE THREAD

**Issue by bvandermeersch** [MRVMV/sequelize-mig#48] opened 2020-10-14 21:11 UTC
thanks for forking this repo and keeping it up to date.

I am unable to create my initial migration file. 

node -v
v12.18.3

npm -v
6.14.8

npx -v
10.2.2

```

npx sequelize-mig migration:make -n initial
(node:27969) ExperimentalWarning: The ESM module loader is experimental.
file:///home/devops/Desktop/project/api/node_modules/sequelize-mig/lib/helpers.js:147
      if (a.depends?.length !== 0) {
                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)

```

Any ideas?

**Comment by MRVMV** [comment] 2020-10-14 22:16
Hey!
I really liked the first one and it deserves supporting :)

for this problem its from Optional chaining, and after some checking, it is a feature supported only from node 14.0.0 and thats why you are getting the problem...
(its alternative to writing if(a.depends.length && a.depends?.length !== 0)...)

Im using it a lot in the project and i didnt see that its not supported to recent updates...

I have two options then, rewrite all of these to make it compatible with old node versions, or just raise the required version to 14.0.0, I will see tomorrow :)

**Comment by MRVMV** [comment] 2020-10-14 23:27
fixed with and it should work now in versions less than 14 :)
#49

**Comment by bvandermeersch** [comment] 2020-10-15 01:43
Thanks for taking the time to do that!

I now have a new issue:

```
TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on linux
    at getPathFromURLPosix (internal/url.js:1330:11)
    at fileURLToPath (internal/url.js:1353:50)
    at finalizeResolution (internal/modules/esm/resolve.js:250:16)
    at moduleResolve (internal/modules/esm/resolve.js:636:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at Loader.import (internal/modules/esm/loader.js:178:28)
    at importModuleDynamically (internal/modules/esm/translators.js:88:26)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:37:14) {
  code: 'ERR_INVALID_FILE_URL_HOST'
}
```

I do not see a flag in the help to set a file_url_host

**Comment by bvandermeersch** [comment] 2020-10-15 13:17
https://nodejs.org/api/errors.html#errors_err_invalid_file_url_host

**Comment by MRVMV** [comment] 2020-10-15 21:27
wlc :)
Its another problem but we will continue with in the same issue
I dont have a linux to try on it actually and never tried one...
anyway i will try to find the problem

**Comment by MRVMV** [comment] 2020-10-19 17:48
@bvandermeersch i didnt find the problem and i never tried linux and cant do that...
if you can try it on your side and see where is the problem. i think its when dynamically import index file but i dont know why anyway

**Comment by signorettif** [comment] 2020-10-20 13:08
I am also having the same issue on Catalina running node 14.13.1

```
TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on darwin
    at getPathFromURLPosix (internal/url.js:1328:11)
    at fileURLToPath (internal/url.js:1351:50)
    at finalizeResolution (internal/modules/esm/resolve.js:255:16)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at Loader.import (internal/modules/esm/loader.js:164:28)
    at importModuleDynamically (internal/modules/esm/translators.js:99:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14) {
  code: 'ERR_INVALID_FILE_URL_HOST'
}
```

**Comment by MRVMV** [comment] 2020-10-25 15:20
I got the idea and I think I got where is that happening but Im not sure how should it be resolved... Im not finding any resources about this over the internet but I will try more @signorettif

**Comment by MRVMV** [comment] 2020-10-25 17:42
@signorettif @bvandermeersch
probably the problem is here in this [line ](https://github.com/MRVMV/sequelize-mig/blob/main/bin/migration/make.js#L61)
which says:
`const { sequelize } = (await import(`file:\\${indexDir}`)).default;`
if you can try to change it locally on your device in ...\node_modules\sequelize-mig\bin\migration\make.js to the following statements one by one and tell me if it makes any difference (btw you can use migartion:make -p so it doesnt make any new file, just shows a preview)

`const { sequelize } = (await import(`file://${indexDir}`)).default;`
`const { sequelize } = (await import(`file:///${indexDir}`)).default;`
`const { sequelize } = (await import(`file:////${indexDir}`)).default;`
`const { sequelize } = (await import(`file:\\\\${indexDir}`)).default;`
`const { sequelize } = (await import(`file://localhost/${indexDir}`)).default;`

im sorry for telling you to do that but i dont have any access to a linux device in the near time so please try these and tell me if any one of them works so we can solve the issue :)

**Closed** 2020-11-15 00:03 UTC

**Comment by cincodenada** [comment] 2021-09-07 22:28
Hello! I'm running into this on OS X and am happy to test. Why is this using a `file:\\` URI in the first place? The following seems to work just fine on my machine, and would be more universal:
```
const { sequelize } = (await import(indexDir)).default
```
